/**
 * Hand-kept (not generated). A page whose body repeats another page -> the
 * page it repeats, which is the one kept (tracker R2). Until the duplicate
 * redirects, it is marked noindex (ContentPage.astro), and links in page,
 * post and bio text (src/lib/links.ts) and the nav cards built by
 * `live()` (src/lib/nav.ts) open the kept page instead. The duplicate keeps
 * its place in the tree, so its own breadcrumb still works.
 *
 * The permanent fix is upstream: a 301 in public/_redirects (and the old
 * addresses pointed straight at the kept page), the nav.json entry's href,
 * and the duplicate's content file dropped — all generated by
 * extract/build_pages.py. An entry here can be deleted once its duplicate is
 * gone from nav.json and src/content.
 */
export const duplicatePages: Record<string, string> = {
  '/brain-regeneration-clinic/long-covid-syndrome/': '/conditions/long-covid-syndrome/',
};
