/**
 * Hand-kept (not generated). An old page that is on its way out -> the page
 * that replaces it (tracker R4). Until it redirects, it is marked noindex with
 * a canonical link to its replacement (ContentPage.astro), so search engines
 * fold it into that page and the site search leaves it out.
 *
 * The two per-doctor request pages are WordPress leftovers: nothing links to
 * them, their bodies repeat the profiles, and their Patient Fusion booking
 * frames no longer display.
 *
 * The permanent fix is upstream, all generated by the extract/ pipeline: a 301
 * from each page to its profile in public/_redirects (with the two older
 * Schwartz addresses pointed straight at her profile), the pages dropped from
 * public/sitemap.xml, and their content files dropped from src/content. An
 * entry here can be deleted once its page is gone from src/content.
 */
export const retiredPages: Record<string, string> = {
  '/dr-porter-request-appointment-page/': '/physicians/jason-porter/',
  '/dr-schwartz-request-appointment-page/': '/physicians/laura-badalamenti-schwartz/',
};
