/**
 * Hand-kept (not generated). A placeholder page -> the finished page on the
 * same topic, for links in page, post and bio text (tracker N1). Applied by
 * the link clean-up in src/lib/links.ts; the words of the link stay as they
 * are. A placeholder link with no entry here loses its link and keeps its
 * words. An entry stops mattering on its own once its placeholder leaves
 * stub-routes.json, and can then be deleted.
 *
 * The permanent fix is upstream: nav.json, stub-routes.json and _redirects
 * are generated by extract/build_pages.py.
 */
export const stubFallbacks: Record<string, string> = {
  '/specialty-labs/food-sensitivity/': '/conditions/igg-food-intolerance/',
  '/conditions/gut-health/': '/conditions/gastrointestinal-disorders/',
  '/conditions/chronic-pain/dysmenorrhea/': '/transcranial-direct-current-stimulation/dysmenorrhea/',
  '/specialty-labs/gut-health/': '/specialty-labs/microbiome-panel/',
  '/conditions/rheumatoid-arthritis/': '/conditions/arthritis/',
};
